### ISSUE TITLE
Potřeba lepší dokumentace

### ISSUE THREAD

**Issue by karelkral** [LaskaKit/ESP32-S3-DEVKit#1]
Já jsem začátečník-před týdnem jsem zapojil své první Arduino-a nadšeně jsem se vrhl do této desky. Ale naprosto mi k ní chybí dokumentace. Vím, že na GitHub je schéma zapojení, ale potřeboval bych nějaký návod, jak s deskou zacházet. Např. v example na Neopixel jsem našel nějakou poznámku a práci se stabilizátorem a pinu 47, ale to je všechno. Co to znamená zapnout output na pinu 47?  Potřebuji více informací. Potřebuji dokumentaci k zapojení konektorů. Jak pracovat s baterií a touto deskou? Píšete, že lze zapojit, ale nikde není, jak. 
Všechny příklady z Githubu mi jedou, ale srozumitelná dokumentace k HW chybí.

**Comment by Konstantin-G** [comment]
Bohužel podrobný návod napsat nestíháme, do budoucna bude datasheet na modul.
